# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Compose
kotlin.compiler.all-open.annotations=androidx.compose.runtime.Composable

# Firebase
google.services.location=app/google-services.json
